/* eslint-disable no-unused-vars */
const places = [
    "Paris",
    "New York",
    "Tokyo",
    "London",
    "Sydney",
    "Florence",
    "Barcelona",
    "Cape Town",
    "Prague",
    "Rio de Janeiro",
    "Los Angeles",
    "Lisbon",
    "Berlin",
    "Dubai",
    "Mumbai",
    "Toronto",
    "Bangkok",
    "Amsterdam",
    "Buenos Aires",
    "Seoul",
    "Venice",
    "Vancouver",
    "Cairo",
    "Singapore",
    "Dublin",
    "Hong Kong",
    "Vienna",
    "Moscow",
]
